service: sls-backend-mongodb

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-1

functions:
  addFavorite:
    handler: handler.add_favorite
    events:
      - http:
          path: add-favorite
          method: post
          cors: true

  listFavorites:
    handler: handler.list_favorites
    events:
      - http:
          path: list-favorites
          method: get
          cors: true

resources:
  Resources:
    FavoritesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: favorites
        AttributeDefinitions:
          - AttributeName: org_id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: org_id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

